app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

////////////////////
// General Routes //
////////////////////
Route::get('/', function () {
    return redirect('/posts');
});

Route::get('soon', function () {
    return view('site.soon');
});

Route::get('about', function () {
    return view('site.about');
});

// Post Routes
Route::post('posts/{id}/cancel', 'PostController@cancel');
Route::resource('posts', 'PostController');

// User Routes
Route::post('users/{uid}/questions/{pid}', 'UserQuestionController@acceptApplicant');
Route::post('users/{uid}/questions/{pid}/request', 'UserQuestionController@requestSolution');
Route::post('users/{uid}/questions/{pid}/accept', 'UserQuestionController@acceptSolution');
Route::get('users/{uid}/questions/{pid}/solution', 'UserQuestionController@getSolution');
Route::put('users/{uid}/questions/{pid}/solution', 'UserQuestionController@updateSolution');
Route::resource('users', 'UserController');
Route::resource('users.questions', 'UserQuestionController');

// Teacher routes
Route::post('teachers/{tid}/lessons/{pid}/adjust', 'TeacherLessonController@adjustQuote');
Route::resource('teachers', 'TeacherController');
Route::resource('teachers.lessons', 'TeacherLessonController');

// Wallet routes
Route::resource('wallets', 'WalletController');
Route::resource('wallets.transactions', 'WalletTransactionController');
Route::resource('wallets.exchanges', 'WalletExchangeController');

//////////////////
// Admin Routes //
//////////////////
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', function () {
        return redirect('admin/posts');
    });
    Route::resource('posts', 'PostController');
    Route::resource('users', 'UserController');
    Route::resource('teachers', 'TeacherController');
    Route::post('wallets/{id}/addTransaction', 'WalletController@addAdjustment');
    Route::resource('wallets', 'WalletController');
    Route::resource('tags', 'TagController');
});

///////////////////////////
// Authentication Routes //
///////////////////////////
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Register routes
Route::get('/register', 'Auth\AuthController@getRegister');
Route::post('/register', 'Auth\AuthController@postRegister');

// Password routes
Route::controllers(['password' => 'Auth\PasswordController']);

app/Models/Teacher.php
<?php

namespace App\Models;

class Teacher extends BaseModel
{
    protected $table      = 'teacher';
    protected $primaryKey = 'teacher_id';
    public $timestamps    = true;

    protected $fillable = [
        'user_id', 'years_of_industry_experience', 'years_of_freelance_experience', 'skills', 'description', 'rating', 'date_created', 'last_updated',
    ];

    /**
     * Get the user record associated with the teacher.
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * Get the certified fields that the teacher is certified in.
     */
    public function certified_fields()
    {
        return $this->belongsToMany('App\Models\CertifiedField', 'teacher_to_certified_field', 'teacher_id', 'certified_field_id');
    }

    /*
     * Get the subscription record associated with the teacher
     */
    public function subscription()
    {
        return $this->hasOne('App\Models\Subscription');
    }

    /**
     * Get the posts the teacher is assigned to
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

    /**
     * Get the posts the teacher has applied to
     */
    public function applied_posts()
    {
        return $this->belongsToMany('App\Models\Post', 'teacher_to_post', 'teacher_id', 'post_id')->withPivot('inactive', 'quoted_price');
    }

    public function getContactAttribute() {
        return $this->user->contact;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $table      = 'user';
    protected $primaryKey = 'user_id';
    public $timestamps    = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'family_name_kanji', 'first_name_kanji', 'family_name_kana', 'first_name_kana', 'date_created', 'last_updated',
    ];

    public $nullable = [
        'family_name_kanji',
        'first_name_kanji',
        'profile_image_path',
        'profile_image_thumbnail_path',
    ];

    public function getNameKanjiAttribute()
    {
        return $this->family_name_kanji . $this->first_name_kanji;
    }

    public function getNameKanaAttribute()
    {
        return $this->family_name_kana . $this->first_name_kana;
    }

    /**
     * Get the contact record associated with the user.
     */
    public function contact()
    {
        return $this->hasOne('App\Models\Contact');
    }

    /**
     * Get the login credential record associated with the user.
     */
    public function login_credential()
    {
        return $this->hasOne('App\Models\LoginCredential');
    }

    /**
     * Get the wallet record associated with the user.
     */
    public function wallet()
    {
        return $this->hasOne('App\Models\Wallet');
    }

    /**
     * Get the posts associated with the user.
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

    /**
     * Get the teacher record associated with the user.
     * This may not be correct
     */
    public function teacher()
    {
        return $this->hasOne('App\Models\Teacher');
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Teacher\UpdateRequest;
use App\Models\CertifiedField;
use App\Models\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teacher::all();
        return view('admin.teachers.index', ['teachers' => $teachers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $teacher = Teacher::findOrFail($id);
        return view('admin.teachers.show', ['teacher' => $teacher]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher     = Teacher::with(['certified_fields'])->findOrFail($id);
        $cert_fields = CertifiedField::all();
        return view('admin.teachers.edit', ['teacher' => $teacher, 'cert_fields' => $cert_fields]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $teacher = Teacher::findOrFail($id);
        $teacher->update($request->all());
        if (is_null($request->certified_fields)) {
            $request->certified_fields = [];
        }
        $teacher->certified_fields()->sync($request->certified_fields);
        return redirect('admin/teachers/' . $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Teacher;
use App\Models\User;
use Auth;
use Gate;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * TODO
     * Display a listing of all the teachers if admin
     * Authorization : Admin
     *
     * Display teacher's profile if teacher else redirect to posts
     * Authorization : Teacher
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('is-teacher')) {
            if (Gate::denies('logged-in')) {
                return redirect('/posts')->with('ok', 'Please log in to view teacher profiles.');
            }
            return redirect('/posts')->with('ok', 'Please specify a teacher');
        }
        $teacher = Auth::user()->user->teacher;
        return redirect('/teachers/' . $teacher->teacher_id);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // N/A
    }

    /**
     * Store a newly created teacher in teacher table
     * Authorization : Admin
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // TODO: implement for admin
    }

    /**
     * Display the specified teacher profile.
     * Authorization : User
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Gate::denies('logged-in')) {
            return redirect('/posts')->with('ok', 'Please log in to view teacher profiles');
        }

        $teacher = Teacher::findOrFail($id);
        return view('site.teachers.show', ['teacher' => $teacher]);
    }

    /**
     * Show the form for editing teacher profile
     * Authorization Admin, Specific Teacher
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = Teacher::findOrFail($id);
        $this->authorize('accessTeacherProfile', $teacher);
        return view('site.teachers.edit', ['teacher' => $teacher]);
    }

    /**
     * Update the specified teacher information in the teacher table.
     * Authorization : Admin, Specific Teacher
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $teacher = Teacher::findOrFail($id);
        $this->authorize('accessTeacherProfile', $teacher);
        $teacher->update($request->all());
        return redirect('teachers/' . $id)->with('ok', 'Teacher has been successfully updated.');
    }

    /**
     * Remove the specified teacher's teacher designation from the database
     * Authorization : Admin
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // TODO: implement for admin
    }
}

resources/views/site/teachers/edit.blade.php
@extends('site')

@section('content')
<div class="col-md-10 col-md-offset-1">
	<h2 class="page-header">Editing Teacher @lang('site.profile')</h2>

	{!! Form::model($teacher, array('route' => array('teachers.update', $teacher->teacher_id), 'method'=>'PUT')) !!}
	<div class="form-group col-md-4">
		{!! Form::label('years_of_industry_experience', trans('site.years_of_industry_experience')) !!}
		{!! Form::number('years_of_industry_experience', null, array('class' => 'form-control')) !!}
	</div>

	<div class="form-group col-md-4">
		{!! Form::label('years_of_freelance_experience', trans('site.years_of_freelance_experience')) !!}
		{!! Form::number('years_of_freelance_experience', null, array('class' => 'form-control')) !!}
	</div>

	<div class="form-group col-md-4">
		{!! Form::label('rating', trans('site.rating')) !!}
		{!! Form::number('rating', null, array('class' =>'form-control', 'readonly')) !!}
	</div>

	<div class="col-md-12">
		<div class="form-group">
			{!! Form::label('skills', trans('site.skills')) !!}
			{!! Form::text('skills', null, array('class' => 'form-control')) !!}
		</div>

		<div class="form-group">
			{!! Form::label('description', trans('site.description')) !!}
			{!! Form::textarea('description', null, array('class' => 'form-control')) !!}
		</div>

		{!! Form::submit('Submit', array('class'=>'btn btn-primary')) !!}
		<a href="{{ url('/teachers/'.$teacher->teacher_id) }}" class="btn btn-default">@lang('actions.cancel')</a>
	</div>

	{!! Form::close() !!}
</div>
@endsection

resources/views/site/teachers/show.blade.php
@extends('site')

@section('content')
<div class="col-md-10 col-md-offset-1">
	<div class="row">
		<div class="col-xs-12">
			<h2 class="user__title page-header">
				{{ $teacher->user->name_kanji }}
			</h2>
		</div>
		<div class="col-md-3">
			<div class="text-center">
				<img src="@if($teacher->user->profile_image_path===null){{ asset('img/default.jpg')}} @else {{ asset($teacher->user->profile_image_path) }} @endif" alt="" class="user-profile__img">
			</div>
			<div class="list-group">
				{{-- TODO: set up email --}}
				@can('access-teacher-profile', $teacher)
				<a class="list-group-item" href="{{ url('/users/'.$teacher->user->user_id) }}">
					<i class="fa fa-user"></i> @lang('site.user')@lang('site.profile')
				</a>
				<a class="list-group-item" href="{{ url('/teachers/'.$teacher->teacher_id.'/edit') }}">
					<i class="fa fa-pencil"></i> Edit @lang('site.profile')
				</a>
				@else
				<button class="btn btn-primary"><i class="fa fa-envelope"></i> Send Email</button>
				<button class="btn btn-disabled"><i class="fa fa-comment"></i> Send Message</button>
				<button class="btn btn-disabled"><i class="fa fa-video-camera"></i> Video Chat</button>
				@endcan
			</div>
		</div>
		<div class="col-md-9">
			<table class="table">
				<tbody>
					<tr>
						<th>@lang('site.years_of_industry_experience')</th>
						<td>{{ $teacher->years_of_industry_experience }}</td>
					</tr>
					<tr>
						<th>@lang('site.years_of_freelance_experience')</th>
						<td>{{ $teacher->years_of_freelance_experience }}</td>
					</tr>
					<tr>
						<th class="col-xs-2">@lang('site.certified_fields')</th>
						<td colspan="3">
							<ul>
								@foreach($teacher->certified_fields as $field)
								<li>{{ $field->field_text }}</li>
								@endforeach
							</ul>
						</td>
					</tr>
					<tr>
						<th>@lang('site.skills')</th>
						<td>{{ $teacher->skills }}</td>
					</tr>
					<tr>
						<th>@lang('site.rating')</th>
						<td>@include('site.teachers.partials.rating', ['rating'=>$teacher->rating])</td>
					</tr>
					<tr>
						<th>@lang('site.description')</th>
						<td>
							{{ $teacher->description }}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
@stop